# Generated by Django 4.2.10 on 2024-02-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='level',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
