# Generated by Django 4.2.9 on 2024-01-27 14:17

from django.db import migrations, models
import django.db.models.deletion
import utils.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='skills.queue')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='skills.skill')),
            ],
            bases=(models.Model, utils.models.fields.AtWhenFields),
        ),
        migrations.CreateModel(
            name='ProgressLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='progress_logs', to='courses.course')),
            ],
            bases=(models.Model, utils.models.fields.AtWhenFields),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notes', to='courses.course')),
            ],
            bases=(models.Model, utils.models.fields.AtWhenFields),
        ),
        migrations.CreateModel(
            name='CoursePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='courses.course')),
            ],
            bases=(models.Model, utils.models.fields.AtWhenFields),
        ),
    ]
