# Generated by Django 4.2.9 on 2024-01-23 13:15

from django.db import migrations, models
import django.db.models.deletion
import utils.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            bases=(models.Model, utils.models.fields.AtWhenFields),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
            bases=(models.Model, utils.models.fields.AtWhenFields),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='skills.queue')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='skills.skill')),
            ],
            bases=(models.Model, utils.models.fields.AtWhenFields),
        ),
    ]
